//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice2
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int order_details_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> quantity { get; set; }
    }
}
