//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice2
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_code { get; set; }
        public string product_image { get; set; }
        public Nullable<System.DateTime> product_date { get; set; }
        public Nullable<int> product_quantity { get; set; }
        public Nullable<int> product_quantity_alert { get; set; }
        public Nullable<double> product_price { get; set; }
        public Nullable<int> cate_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<int> unit_id { get; set; }
    }
}
