//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int setting_id { get; set; }
        public string setting_name { get; set; }
        public string setting_phone { get; set; }
        public string setting_logo { get; set; }
        public string setting_address { get; set; }
        public string setting_email { get; set; }
    }
}
