//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice2
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int user_id { get; set; }
        public string user_code { get; set; }
        public string user_fullname { get; set; }
        public string user_address { get; set; }
        public string user_phone { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public Nullable<System.DateTime> user_date { get; set; }
        public Nullable<int> user_kind_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> branch_id { get; set; }
    }
}
